# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCP-UDP_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'CocoaAsyncSocket'
  # Pods for TCP-UDP_Demo

  target 'TCP-UDP_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TCP-UDP_DemoUITests' do
    # Pods for testing
  end

end
